dist: trusty
group: travis_latest
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - cppcheck

script:
  - /usr/bin/g++-8 -dumpfullversion
  - make clean all V=1 CXX=/usr/bin/g++-8 CC=/usr/bin/gcc-8
  - for i in bin/*; do ${i}; done
