dist: trusty
group: travis_latest
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - cppcheck

script:
  - /usr/bin/g++-7 -dumpfullversion
  - make clean all V=1 CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7
  - for i in bin/*; do ${i}; done
